---
- name: Install Clickhouse
  hosts: clickhouse
  tags: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb
            dest: ./{{ item }}_{{ clickhouse_version }}.deb
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
            dest: ./clickhouse-common-static_{{ clickhouse_version }}.deb
            mode: "0644"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "./{{ item }}"
      with_items:
        - clickhouse-common-static_{{ clickhouse_version }}.deb
        - clickhouse-client_{{ clickhouse_version }}.deb
        - clickhouse-server_{{ clickhouse_version }}.deb
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Wait for clickhouse-server to get ready
      ansible.builtin.pause:
        seconds: 30
        echo: false
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tags: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
        dest: ./vector-{{ vector_version }}-amd64.deb
        mode: "0644"

    - name: Install Vector packages
      become: true
      ansible.builtin.apt:
        deb: ./vector-{{ vector_version }}-amd64.deb
      notify:
        - Start Vector service

    - name: Copy vector config
      become: true
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: /etc/vector/vector.yaml
        mode: '0644'
      notify:
        - Start Vector service

- name: Install NGINX
  hosts: lighthouse
  tags: lighthouse
  become: true
  handlers:
    - name: NGINX | Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      listen: start nginx
    - name: NGINX | Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: reload nginx
  tasks:
    - name: NGINX | Add nginx apt-key
      ansible.builtin.apt_key:
        url: http://nginx.org/keys/nginx_signing.key
        state: present
    - name: NGINX | Add nginx apt repository
      ansible.builtin.apt_repository:
        repo: 'deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'
        state: present
        filename: nginx
        update_cache: true
    - name: NGINX | Install
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      notify: start nginx
    - name: NGINX | Create general config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: reload nginx

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: NGINX | Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: reload nginx
  pre_tasks:
    - name: Lighthouse | install dependencies
      ansible.builtin.apt:
        name: git
        state: present

  tasks:
    - name: Lighthouse | Get from source
      ansible.builtin.git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location }}"
    - name: Wait for nginx to get ready
      ansible.builtin.pause:
        seconds: 30
        echo: false
    - name: Lighthouse | Create Lighthouse config
      become: true
      ansible.builtin.template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: reload nginx
